-- MySQL Script generated by MySQL Workbench
-- Thu Mar  5 08:47:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema captiveportal_stats
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema captiveportal_stats
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `captiveportal_stats` DEFAULT CHARACTER SET utf8 ;
USE `captiveportal_stats` ;

-- -----------------------------------------------------
-- Table `captiveportal_stats`.`logins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captiveportal_stats`.`logins` (
  `id` INT NOT NULL,
  `code` VARCHAR(45) NULL,
  `durantion` INT(10) NULL,
  `mac` VARCHAR(20) NULL,
  `ip` VARCHAR(15) NULL,
  `time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captiveportal_stats`.`logouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captiveportal_stats`.`logouts` (
  `id` INT NOT NULL,
  `code` VARCHAR(45) NULL,
  `durantion` INT(10) NULL,
  `mac` VARCHAR(20) NULL,
  `ip` VARCHAR(15) NULL,
  `time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `captiveportal_stats`.`failures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captiveportal_stats`.`failures` (
  `id` INT NOT NULL,
  `code` VARCHAR(45) NULL,
  `error` VARCHAR(45) NULL,
  `errorMsg` VARCHAR(45) NULL,
  `mac` VARCHAR(20) NULL,
  `ip` VARCHAR(15) NULL,
  `time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
